### ISSUE TITLE
Cannot build due to fatal error: Running "imagemin:dist" (imagemin) task Fatal error: Cannot read property 'contents' of undefined

### ISSUE THREAD

**Issue by mrgix** [matheushf/generator-angularfire-express#4]
I'm trying to build the application out of the box to test if it will run on my hosting.

But when i'm building the package with the build grunt tast. I'm getting the following error:

Running "imagemin:dist" (imagemin) task
Fatal error: Cannot read property 'contents' of undefined

So i was debugging it and running the task seperatly and getting the same error:
Looking for a solution i'm getting the following: https://github.com/gruntjs/grunt-contrib-imagemin/issues/208

Doesn't matter if this works or not i want to get a package that i can deploy what is the best thing i can do?

**Comment by matheushf** [comment]
You can use `grunt build --force` while I fix this

**Comment by mrgix** [comment]
This did the trick! Thank you!
