### ISSUE TITLE
whenAuthenticated method

### ISSUE THREAD

**Issue by supadupdip** [matheushf/generator-angularfire-express#6]
I've been reading through some of the files that this generator creates for applications and saw that there's a commented block that was supposed to be used to provide route security. Is this functionality going to be added in future releases or is it going to be dropped? Can you highlight what issues you were having with the new SDK that lead you to commenting this out?

**Comment by matheushf** [comment]
Sorry, I can't remember exactly what was happening, I should have made a better comment about the issues. But I will check this out and try to add secure routes again.

Thanks by the report!
